### ISSUE TITLE
Can I have an explanation

### ISSUE THREAD

**Issue by wyatt** [Galaxy-MSM8916/android_device_samsung_gt58ltetmo#1]
I have a SM-T357T (gt58ltetmo) and would like to know how to put lineage 15.1 on it. I am fairly new to building roms and I don't understand what I need to do

**Comment by r3pwn** [comment]
Right now, it's not exactly in a usable phase. It boots and and everything besides audio is working (with the possible additional exception of RIL). The problem with audio that we're running into is that the device uses a tfa9895 audio amp, and Samsung implemented the code for it very poorly, and in a way that makes it not very easy for us to just go and re-add it ourselves. When it's ready, there will probably be a post on XDA about it, or something.

**Comment by wyatt** [comment]
Thanks for the response, I'm glad that this device is being developed in some way. Do you have a rough idea of when this porting guide would be ready

**Comment by wyatt** [comment]
Thanks again for the quick response
